name: Static Code Analysis

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mypy and ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Run ruff lint
        run: ruff check --config ruff.toml .

      - name: Run ruff format
        run: ruff format --check --config ruff.toml .
